In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from graphviz import Source
import matplotlib.pyplot as plt
from utiles import plot_decision_boundary
import pandas as pd
import numpy as np

In [2]:
datos = pd.read_csv('./data/juego_tennis.csv')

In [3]:
datos

Pronóstico Temperatura Humedad Viento Juega_Tennis
0     soleado       calor    alta     no           No
1     soleado       calor    alta     si           No
2     nublado       calor    alta     no           Si
3    lluvioso    moderado    alta     no           Si
4    lluvioso        frío  normal     no           Si
5    lluvioso        frío  normal     si           No
6     nublado        frío  normal     si           Si
7     soleado    moderado    alta     no           No
8     soleado        frío  normal     no           Si
9    lluvioso    moderado  normal     no           Si
10    soleado    moderado  normal     si           Si
11    nublado    moderado    alta     si           Si
12    nublado       calor  normal     no           Si
13   lluvioso    moderado    alta     si           No

In [7]:
X = datos.iloc[:, 0:-1]
y = datos.iloc[:, -1]
print(X.shape)
print(y.shape)

(14, 4)
(14,)


In [8]:
from sklearn.compose import ColumnTransformer
categorical_columns = ['Pronóstico', 'Temperatura', 'Humedad', 'Viento']

In [23]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)

column_transformer = ColumnTransformer(
    transformers=[('encoder', encoder, categorical_columns)],
    remainder='passthrough'  # Mantener las columnas no especificadas sin cambios
)

In [18]:
encoded_X = column_transformer.fit_transform(X)

c:\Users\yarmu\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [19]:
print(encoded_X)

[[0. 0. 1. 1. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 1.]]


In [20]:
tree_clf = DecisionTreeClassifier(max_depth=3, random_state=42)
tree_clf.fit(encoded_X, y)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [25]:
from sklearn.tree import export_graphviz
import graphviz

dot_data = export_graphviz(tree_clf, out_file=None, 
                           class_names=y.unique().astype(str),
                           filled=True, rounded=True, special_characters=True)

graph = graphviz.Source(dot_data)
graph.render("arbol_decision")
graph.view("arbol_decision")


'arbol_decision.pdf'